---
-
  name: additional programming languages
  hosts: local
  gather_facts: false
  tasks:

    - name: install additional languages
      homebrew: name={{ item }} state=present
      with_items:
        - go
        - haskell-platform
