---
-
  name: development libraries
  hosts: local
  gather_facts: false
  tasks:

    - name: install development libraries
      homebrew: name={{ item }} state=present
      with_items:
        - libevent
        - libmemcached
        - libxml2
