---
-
  name: development backing servers
  hosts: local
  gather_facts: false
  tasks:

    - name: install backing services
      homebrew: name={{ item }} state=present
      with_items:
        - redis
        - memcached
        - elasticsearch

    - name: Add my plsql config file
      copy: >
        dest=~/.psqlrc
        src=templates/psqlrc
