---
-
  name: development backing servers
  hosts: local
  gather_facts: false
  tasks:

    - name: install backing services
      homebrew: name={{ item }} state=present
      with_items:
        - redis
        - memcached
        - elasticsearch
