---
-
  name: CLI tools
  hosts: local
  gather_facts: false
  tasks:

    - name: install CLI tools
      homebrew: name={{ item }} state=present
      with_items:
        - mercurial
        - tmux
        - tree
        - augeas
        - readline
        - s3cmd
        - siege
        - tarsnap
        - wget
        - heroku-toolbelt
        - ack
        - hub
        - ctags
        - sloccount

    - name: Install npm based tools
      npm: name={{ item }} global=yes state=present
      with_items:
        - dalek-cli
