---
- name: install virtualenv
  command: >
    /usr/local/bin/pip install virtualenv
    creates=/usr/local/bin/virtualenv

- name: Install OpenSSL for Python
  homebrew:
    name: openssl
    state: linked

- name: Install Python versions
  homebrew: name={{ item }} state=present
  with_items:
    - python
    - python3

- name: Add pip directory
  file:
    name: ~/.pip
    state: directory

- name: Setup pip configuration
  copy: >
    dest=~/.pip/pip.conf
    src=pip.conf
