---
- name: install zsh
  homebrew: name=zsh state=latest
  when: ansible_os_family == 'Darwin'
  tags: zsh

- name: add zsh to list of shells
  lineinfile: >
    backup=yes
    dest=/etc/shells
    regexp=^/usr/local/bin/zsh
    line=/usr/local/bin/zsh
  when: ansible_os_family == 'Darwin'
  become: true

- name: change to zsh (Mac)
  shell: chsh -s /usr/local/bin/zsh {{ ansible_env.USER }}
  when: ansible_os_family == 'Darwin'

- name: change to zsh (Ubuntu)
  shell: chsh -s /usr/bin/zsh {{ ansible_env.USER }}
  when: ansible_os_family == 'Ubuntu'

- name: install prezto
  git: repo=https://github.com/bennylope/prezto.git
       dest=~/.zprezto
       version=4f19700919c8ebbaf75755fc0d03716d13183f49
       recursive=yes
  tags: zsh

- name: add zshrc file
  copy: src=zshrc dest=~/.zshrc
  tags: zsh

- name: Link zpreztorc
  file:
    dest: ~/.zpreztorc
    src: ~/.zprezto/runcoms/zpreztorc
    state: link
  tags: zsh
