---
- name: Install Node (Mac)
  homebrew: name=node state=present
  when: ansible_os_family == 'Darwin'

- name: Install npm based tools
  npm: name={{ item }} global=yes state=present
  with_items:
    - dalek-cli
  when: ansible_os_family == 'Darwin'
