---
- name: install vim (Mac)
  homebrew: name={{ item }} state=present
  with_items:
    - vim
  when: ansible_os_family == 'Darwin'

- name: tap neovim (Mac)
  homebrew_tap:
    name: neovim/neovim
    state: present
  when: ansible_os_family == 'Darwin'

- name: install neovim (Mac)
  homebrew: name={{ item }} state=present
  with_items:
    - neovim
  when: ansible_os_family == 'Darwin'

- name: install vim (Ubuntu)
  apt: pkg=vim state=present
  when: ansible_os_family == 'Ubuntu'
